### ISSUE TITLE
문장에서 명사를 추출하지 못했을 때 Exception이 발생합니다

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team18#10]
현재 구조에서는 입력받은 문장에서 명사를 추출하는 것으로 알고 있습니다. 하지만 영어로 이루어진 문장 혹은 일부 한글 문장의 경우 명사를 추출하지 못하게 되는데, 이런 경우 아래와 같은 Exception이 발생합니다. 아래는 입력으로 `고마워`를 넣었을 때의 오류 내용입니다. 

**Exception Logs (Python 3.6, Windows 10)**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "Recommend_tags.py", line 98, in click
    resultList = nouns(str.get())
  File "Recommend_tags.py", line 37, in nouns
    postKwords.extend(keyword_counted.search_key(count_list, freq_data, loop))
TypeError: 'int' object is not iterable
```

Exception을 제거하고 명사가 추출되지 않았을 때의 로직을 작성할 필요가 있습니다.

**Comment by njw1204** [comment]
이 문제를 해결하는 Pull request #11 을 등록했습니다.

**Comment by nh7881** [comment]
> 현재 구조에서는 입력받은 문장에서 명사를 추출하는 것으로 알고 있습니다. 하지만 영어로 이루어진 문장 혹은 일부 한글 문장의 경우 명사를 추출하지 못하게 되는데, 이런 경우 아래와 같은 Exception이 발생합니다. 아래는 입력으로 `고마워`를 넣었을 때의 오류 내용입니다.
> 
> **Exception Logs (Python 3.6, Windows 10)**
> 
> ```
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\tkinter\__init__.py", line 1702, in __call__
>     return self.func(*args)
>   File "Recommend_tags.py", line 98, in click
>     resultList = nouns(str.get())
>   File "Recommend_tags.py", line 37, in nouns
>     postKwords.extend(keyword_counted.search_key(count_list, freq_data, loop))
> TypeError: 'int' object is not iterable
> ```
> 
> Exception을 제거하고 명사가 추출되지 않았을 때의 로직을 작성할 필요가 있습니다.

말씀하신 사항 잘 들었습니다. 저희 코드의 경우 2개 이상의 명사를 가진 게시글만 추천하고 있습니다. 이 부분이 Read me에 누락되어 있는 것을 확인하였습니다.  Read me 수정하여 올리겠습니다.
