### ISSUE TITLE
UX 면에서의 각종 불편함을 해결합시다

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team18#16]
1. okt.nouns()를 처음 호출했을때 무거운 초기화 작업이 발생하여 시간이 오래 걸립니다. 사용자로써는 렉이 걸리는 것처럼 느껴집니다. 미리 로딩시켜 빠르게 동작할 수 있도록 합시다.
2. 본문 입력창이 한 줄이라 여러 줄의 글을 사용할 수 없고 편집에 불편함이 있습니다. 이를 개선한 GUI가 필요합니다.

**Comment by EJLEE5826** [comment]
#15  해결 감사합니다.
