### ISSUE TITLE
Manual - Environment configuration 에 질문이 있습니다.

### ISSUE THREAD

**Issue by Jiseokmin** [CAU-OSS-2019/team-project-team18#17]
README.md를 보고 설치를 했습니다.

1.  
<code> $ pip install --upgrade gensim </code> 
<code> $ pip install --upgrade pip </code> 
<code> $ conda -c conda-forge install jpype1 </code> 
<code> $ pip install konlpy </code> 

![설치중1](https://user-images.githubusercontent.com/28971360/59268589-fdeaae00-8c87-11e9-92c3-829dda7c0355.png)
관리자 권한으로 cmd를 다시 실행하여 아래와 같이 입력했습니다.
![설치중2](https://user-images.githubusercontent.com/28971360/59269669-97b35a80-8c8a-11e9-9242-7dc45e124c56.png)

2.  
<code> $ conda install -c conda-forge gensim 
</code> 
<code> $ pip install --upgrade pip </code> 
<code> $ conda -c conda-forge install jpype1 </code> 
<code> $ pip install konlpy </code> 

![콘다1](https://user-images.githubusercontent.com/28971360/59269997-5c655b80-8c8b-11e9-9e50-684f298f44ba.png)
![콘다2](https://user-images.githubusercontent.com/28971360/59270267-02b16100-8c8c-11e9-9489-41b86de94a1e.png)
![콘다3](https://user-images.githubusercontent.com/28971360/59270278-0ba23280-8c8c-11e9-8cb1-bbe60e245be8.png)

두가지 모두 <code> $ conda -c conda-forge install jpype1 </code> 를 입력했을때
<code>CommandNotFoundError: No command 'conda conda-forge'.</code> 라는 오류가 떴습니다.
제가 뭔가를 놓치고 있는건가요 혹은 readme가 잘못된 걸까요..?

gui는 실행이 되지만 
막상 "계단 그림자 기다리는 중. 필카의 묘미." 로 예시를 입력하고 
process버튼을 누르면
가장 마지막 사진의 하단부처럼 에러가 뜹니다. 

답변 해주시면 감사드리겠습니다.

다른 사람의 아이디로 로그인 된 상태에서 issue를 등록해버렸습니다 ㅜㅜㅜ
h-dyeon, helenhdy@naver.com의 이름으로 다시 올리겠습니다.

**Comment by h-dyeon** [comment]
피씨실에 있는 컴퓨터로 이슈를 적다보니 
다른사람의 아이디로 이미 로그인 된 상태라는걸 미처 확인하지 못했습니다 
죄송합니다ㅜㅜㅜ 지워주시면 감사하겠습니다 ㅜㅜ

**Comment by Jiseokmin** [comment]
불편드려 죄송합니다.. 제가 미쳐 로그아웃 하는 것을 까먹고 그냥 간 것 같습니다..
제가 깃을 잘 몰라서 그런데 이슈를 close 했는데 이렇게 하면 되나요??

**Comment by EJLEE5826** [comment]
네 #18로 확인하겠습니다!
