### ISSUE TITLE
해당 기능에 맞게 인스타그램을 띄워주면 어떠겠습니까?

### ISSUE THREAD

**Issue by canis617** [CAU-OSS-2019/team-project-team18#31]
인스타그램 관련 프로그램인데 바로 인스타 창이 준비되어 있으면 좋겠다 싶었습니다.
싶어서 프로그램 실행시 브라우저로 인스타그램 홈페이지를 띄우는 프로그램을 제작해 보았습니다.

해당 프로그램을 fork와 함께 pull request 넣겠으니 확인 부탁드리고 merge 병합을 고려해주시면 감사하겠습니다.

**Comment by choijihyuk** [comment]
아이디어 감사합니다. 저희가 인스톨할 api가 많아서 혹시  중간에 막히시면 바로 말씀해주시면 도와드리겠스니다.

**Comment by choijihyuk** [comment]
브라우저 창이 시작과 동시에 자동으로 띄워지는 형태라 제가 버튼을 따로 생성해서 버튼을 누르면 브라우저가 뜨게 추가 구현을 해보겠습니다.

**Comment by canis617** [comment]
그런 방법을 사용하면 더 좋겠네요 감사합니다

**Comment by canis617** [comment]
해당 이슈에 대한 내용을 제가 버튼으로 구현해 보았습니다.
시간이 남아 추가적으로 구현하였으니 이미 구현한것이 있으시면 쓰셔도 괜찮고
퀄리티가 안좋다고 생각하시면 안쓰셔도 상관없습니다. 이미지 첨부합니다.
![image](https://user-images.githubusercontent.com/38325657/59913367-fcbd3c00-9452-11e9-9759-07c42216cfde.png)

해당 instagram 아이콘을 클릭하면 인스타 그램이 켜집니다.

**Comment by choijihyuk** [comment]
수고많으셨고 좋은 아이디어와 구현 감사합니다.
