### ISSUE TITLE
새로운 input 입력시 output 초기화에 관하여

### ISSUE THREAD

**Issue by 97e57e** [CAU-OSS-2019/team-project-team18#7]
예를들어 input에 계단 그림자 기다리는중, 햄버거 맛있따를 순서대로 입력하면

output textbox에 #그림자 #계단 #햄버거 와같이 뒤에 계속 쌓이게 됩니다. 

의도하신것인지는 모르겠으나 process버튼을 눌러 새 input을 입력할때 output textbox를 초기화 해주거나 delete버튼을 만들어 사용자가 선택적으로 간단하게 초기화 할 수 있다면 사용자 입장에서 더 편리할것 같습니다.

**Comment by EJLEE5826** [comment]
말씀하신 사항을 반영하여 체크박스로 초기화 여부를 선택할 수 있도록 했습니다. 곧 master에 반영하겠습니다. 감사합니다.

**Comment by nh7881** [comment]
> 예를들어 input에 계단 그림자 기다리는중, 햄버거 맛있따를 순서대로 입력하면
> 
> output textbox에 #그림자 #계단 #햄버거 와같이 뒤에 계속 쌓이게 됩니다.
> 
> 의도하신것인지는 모르겠으나 process버튼을 눌러 새 input을 입력할때 output textbox를 초기화 해주거나 delete버튼을 만들어 사용자가 선택적으로 간단하게 초기화 할 수 있다면 사용자 입장에서 더 편리할것 같습니다.

말씀하신거 수정 완료했습니다.
![image](https://user-images.githubusercontent.com/24385575/58548629-a50d2580-8244-11e9-9400-4aa855159be2.png)

**Comment by 97e57e** [comment]
확인했습니다 감사합니다!
